export const fallbackReviewData = {
  generatedFrom: "demo fallback",
  clientId: "demo-isitme-merkezi",
  clientName: "Demo Isitme Merkezi",
  portalUsers: [
    {
      userId: "demo-mukellef-user",
      displayName: "Demo mukellef kullanicisi",
      role: "client_user",
    },
  ],
  uploadQueue: [
    {
      id: "demo-upload-1",
      fileName: "rexton-alis-faturasi.pdf",
      kind: "invoice",
      uploadedBy: "Demo Isitme Merkezi",
      status: "export_ready",
      uploadedAt: "01.06.2026 10:12",
    },
    {
      id: "demo-upload-2",
      fileName: "mayis-banka-ekstresi.xlsx",
      kind: "bank",
      uploadedBy: "Demo Isitme Merkezi",
      status: "processing",
      uploadedAt: "01.06.2026 10:18",
    },
  ],
  summary: {
    chartRunCount: 1,
    invoiceRowCount: 3,
    autoReadyCount: 1,
    reviewRequiredCount: 2,
    cannotDraftCount: 0,
    allDraftsBalanced: true,
  },
  chartRuns: [
    {
      chartFileName: "DEMO ISITME MERKEZI HESAP PLANI.xlsx",
      accountCount: 593,
      detailAccountCount: 255,
      customerCandidateCount: 20,
      supplierCandidateCount: 37,
      hasPurchaseVat191: true,
      hasSalesVat391: true,
      autoReadyCount: 1,
      reviewRequiredCount: 2,
      cannotDraftCount: 0,
      selectedAccounts: {
        expense_account: "770.01",
        purchase_vat_account: "191.01",
        supplier_account: "320.01",
        bank_account: "102.01",
      },
    },
  ],
  invoiceRows: [
    {
      chartFileName: "DEMO ISITME MERKEZI HESAP PLANI.xlsx",
      fileName: "rexton-alis-faturasi.pdf",
      providerHint: "Rexton Medikal",
      invoiceType: "ALIS",
      issueDate: "01.04.2026",
      payableTotal: "12000.00",
      vatRates: ["20"],
      status: "auto_ready",
      draftQuality: "full_basic_purchase",
      isBalanced: true,
      riskFlags: [],
      parseNotes: [],
      reviewReasonCodes: [],
      productLineHint: "Rexton RLi 20",
      productCategory: "isitme_cihazi",
      productConfidence: 91,
      businessRelevanceStatus: "uygun",
      businessRelevanceConfidence: 91,
      businessRelevanceReason: "Kalem isitme merkezi faaliyet profiliyle uyumlu gorunuyor.",
      businessRelevanceEvidence: ["matched:rexton", "activity_match:hearing_center"],
      aiClassificationUsed: false,
      aiClassificationProvider: "static_rules",
      aiClassificationSkippedReason: "static_high_confidence",
      aiClassificationReason: "",
      aiEstimatedInputChars: 26,
      learningRuleApplied: false,
      learningRuleScope: "",
      learningRuleReason: "",
      exportStatus: "export_ready",
      selectedExpenseAccount: "770.01",
      selectedVatAccount: "191.01",
      selectedSupplierAccount: "320.01.015",
      counterpartyMatchCode: "320.01.015",
      counterpartyMatchConfidence: 100,
      counterpartyMatchReason: "tax_id_exact",
      draftLines: [
        { account_code: "770.01", description: "Alis gideri", debit: "10000.00", credit: "0.00" },
        { account_code: "191.01", description: "Indirilecek KDV", debit: "2000.00", credit: "0.00" },
        { account_code: "320.01.015", description: "Satici cari", debit: "0.00", credit: "12000.00" },
      ],
    },
    {
      chartFileName: "DEMO ISITME MERKEZI HESAP PLANI.xlsx",
      fileName: "urban-care-market.pdf",
      providerHint: "Market Tedarik",
      invoiceType: "ALIS",
      issueDate: "02.04.2026",
      payableTotal: "450.00",
      vatRates: ["20"],
      status: "review_required",
      draftQuality: "partial_review_required",
      isBalanced: true,
      riskFlags: [],
      parseNotes: [],
      reviewReasonCodes: [],
      productLineHint: "Urban Care sac bakim seti",
      productCategory: "kisisel_bakim_kozmetik",
      productConfidence: 92,
      businessRelevanceStatus: "is_alani_disi",
      businessRelevanceConfidence: 92,
      businessRelevanceReason: "Kalem kisisel kullanim veya faaliyet disi harcama riski tasiyor.",
      businessRelevanceEvidence: ["matched:urban care", "personal_use_category"],
      aiClassificationUsed: false,
      aiClassificationProvider: "static_rules",
      aiClassificationSkippedReason: "static_high_confidence",
      aiClassificationReason: "",
      aiEstimatedInputChars: 36,
      learningRuleApplied: false,
      learningRuleScope: "",
      learningRuleReason: "",
      exportStatus: "review_required",
      selectedExpenseAccount: "770.01",
      selectedVatAccount: "191.01",
      selectedSupplierAccount: "320.01.020",
      counterpartyMatchCode: "320.01.020",
      counterpartyMatchConfidence: 82,
      counterpartyMatchReason: "title_similarity",
      draftLines: [
        { account_code: "770.01", description: "Kontrol bekleyen gider", debit: "375.00", credit: "0.00" },
        { account_code: "191.01", description: "Indirilecek KDV", debit: "75.00", credit: "0.00" },
        { account_code: "320.01.020", description: "Satici cari", debit: "0.00", credit: "450.00" },
      ],
    },
    {
      chartFileName: "DEMO ISITME MERKEZI HESAP PLANI.xlsx",
      fileName: "bilinmeyen-tedarikci.pdf",
      providerHint: "Yeni Tedarikci A.S.",
      invoiceType: "ALIS",
      issueDate: "03.04.2026",
      payableTotal: "999.90",
      vatRates: ["20"],
      status: "review_required",
      draftQuality: "partial_review_required",
      isBalanced: true,
      riskFlags: [],
      parseNotes: [],
      reviewReasonCodes: ["counterparty_not_found"],
      productLineHint: "Kolay Soft e-fatura hizmeti",
      productCategory: "e_fatura_hizmeti",
      productConfidence: 94,
      businessRelevanceStatus: "genel_gider",
      businessRelevanceConfidence: 94,
      businessRelevanceReason: "Kalem sektorler arasi genel gider niteliginde gorunuyor.",
      businessRelevanceEvidence: ["matched:kolay soft", "general_expense"],
      aiClassificationUsed: false,
      aiClassificationProvider: "static_rules",
      aiClassificationSkippedReason: "static_high_confidence",
      aiClassificationReason: "",
      aiEstimatedInputChars: 45,
      learningRuleApplied: false,
      learningRuleScope: "",
      learningRuleReason: "",
      exportStatus: "review_required",
      selectedExpenseAccount: "770.01",
      selectedVatAccount: "191.01",
      selectedSupplierAccount: "320.01",
      counterpartyMatchCode: "",
      counterpartyMatchConfidence: 0,
      counterpartyMatchReason: "not_found",
      draftLines: [
        { account_code: "770.01", description: "Gider", debit: "833.25", credit: "0.00" },
        { account_code: "191.01", description: "Indirilecek KDV", debit: "166.65", credit: "0.00" },
        { account_code: "320.01", description: "Satici cari", debit: "0.00", credit: "999.90" },
      ],
    },
  ],
};
