export const fallbackReviewData = {
  generatedFrom: "Private pilot demo verisi",
  clientId: "pilot-isitme-merkezi",
  clientName: "Pilot İşitme Merkezi",
  portalUsers: [
    {
      userId: "pilot-mukellef-user",
      displayName: "Pilot mükellef kullanıcısı",
      role: "client_user",
    },
  ],
  uploadQueue: [
    {
      id: "demo-upload-1",
      fileName: "rexton-alis-faturasi.pdf",
      kind: "invoice",
      uploadedBy: "Pilot İşitme Merkezi",
      status: "export_ready",
      uploadedAt: "01.06.2026 10:12",
    },
    {
      id: "demo-upload-2",
      fileName: "mayis-banka-ekstresi.xlsx",
      kind: "bank",
      uploadedBy: "Pilot İşitme Merkezi",
      status: "processing",
      uploadedAt: "01.06.2026 10:18",
    },
  ],
  summary: {
    chartRunCount: 1,
    invoiceRowCount: 4,
    autoReadyCount: 1,
    reviewRequiredCount: 3,
    cannotDraftCount: 0,
    allDraftsBalanced: true,
  },
  chartRuns: [
    {
      chartFileName: "PİLOT İŞİTME MERKEZİ HESAP PLANI.xlsx",
      accountCount: 593,
      detailAccountCount: 255,
      customerCandidateCount: 20,
      supplierCandidateCount: 37,
      hasPurchaseVat191: true,
      hasSalesVat391: true,
      autoReadyCount: 1,
      reviewRequiredCount: 2,
      cannotDraftCount: 0,
      selectedAccounts: {
        expense_account: "770.01",
        purchase_vat_account: "191.01",
        supplier_account: "320.01",
        bank_account: "102.01",
      },
    },
  ],
  invoiceRows: [
    {
      chartFileName: "PİLOT İŞİTME MERKEZİ HESAP PLANI.xlsx",
      fileName: "rexton-alis-faturasi.pdf",
      providerHint: "Rexton Medikal",
      invoiceType: "ALIS",
      issueDate: "01.04.2026",
      payableTotal: "12000.00",
      vatRates: ["20"],
      status: "auto_ready",
      draftQuality: "full_basic_purchase",
      isBalanced: true,
      riskFlags: [],
      parseNotes: [],
      reviewReasonCodes: [],
      productLineHint: "Rexton RLi 20",
      productCategory: "İşitme cihazı",
      productConfidence: 91,
      businessRelevanceStatus: "uygun",
      businessRelevanceConfidence: 91,
      businessRelevanceReason: "Kalem işitme merkezi faaliyet profiliyle uyumlu görünüyor.",
      businessRelevanceEvidence: ["matched:rexton", "activity_match:hearing_center"],
      aiClassificationUsed: false,
      aiClassificationProvider: "static_rules",
      aiClassificationSkippedReason: "static_high_confidence",
      aiClassificationReason: "",
      aiEstimatedInputChars: 26,
      learningRuleApplied: false,
      learningRuleScope: "",
      learningRuleReason: "",
      exportStatus: "export_ready",
      selectedExpenseAccount: "770.01",
      selectedVatAccount: "191.01",
      selectedSupplierAccount: "320.01.015",
      counterpartyMatchCode: "320.01.015",
      counterpartyMatchConfidence: 100,
      counterpartyMatchReason: "tax_id_exact",
      processingMode: "controlled_automation",
      draftDecisionSource: "deterministic_rules",
      deterministicChecks: ["amount_positive", "single_vat_rate", "balanced_entry", "counterparty_matched", "client_onboarding_ready"],
      exportGateReason: "Deterministik kontroller temiz; export paketine alınabilir.",
      draftLines: [
        { account_code: "770.01", description: "Alış gideri", debit: "10000.00", credit: "0.00" },
        { account_code: "191.01", description: "İndirilecek KDV", debit: "2000.00", credit: "0.00" },
        { account_code: "320.01.015", description: "Satıcı cari", debit: "0.00", credit: "12000.00" },
      ],
    },
    {
      chartFileName: "PİLOT İŞİTME MERKEZİ HESAP PLANI.xlsx",
      fileName: "urban-care-market.pdf",
      providerHint: "Market Tedarik",
      invoiceType: "ALIS",
      issueDate: "02.04.2026",
      payableTotal: "450.00",
      vatRates: ["20"],
      status: "review_required",
      draftQuality: "partial_review_required",
      isBalanced: true,
      riskFlags: [],
      parseNotes: [],
      reviewReasonCodes: [],
      productLineHint: "Urban Care saç bakım seti",
      productCategory: "Kişisel bakım / kozmetik",
      productConfidence: 92,
      businessRelevanceStatus: "is_alani_disi",
      businessRelevanceConfidence: 92,
      businessRelevanceReason: "Kalem kişisel kullanım veya faaliyet dışı harcama riski taşıyor.",
      businessRelevanceEvidence: ["matched:urban care", "personal_use_category"],
      aiClassificationUsed: false,
      aiClassificationProvider: "static_rules",
      aiClassificationSkippedReason: "static_high_confidence",
      aiClassificationReason: "",
      aiEstimatedInputChars: 36,
      learningRuleApplied: false,
      learningRuleScope: "",
      learningRuleReason: "",
      exportStatus: "review_required",
      selectedExpenseAccount: "770.01",
      selectedVatAccount: "191.01",
      selectedSupplierAccount: "320.01.020",
      counterpartyMatchCode: "320.01.020",
      counterpartyMatchConfidence: 82,
      counterpartyMatchReason: "title_similarity",
      processingMode: "ai_assisted_draft",
      draftDecisionSource: "static_rules_ai_assisted_draft",
      deterministicChecks: ["amount_positive", "single_vat_rate", "balanced_entry", "counterparty_low_confidence", "client_onboarding_ready"],
      exportGateReason: "AI destekli taslak modu: fiş taslağı hazır, müşavir onayı olmadan export kapalı.",
      draftLines: [
        { account_code: "770.01", description: "Kontrol bekleyen gider", debit: "375.00", credit: "0.00" },
        { account_code: "191.01", description: "İndirilecek KDV", debit: "75.00", credit: "0.00" },
        { account_code: "320.01.020", description: "Satıcı cari", debit: "0.00", credit: "450.00" },
      ],
    },
    {
      chartFileName: "PİLOT İŞİTME MERKEZİ HESAP PLANI.xlsx",
      fileName: "bilinmeyen-tedarikci.pdf",
      providerHint: "Yeni Tedarikçi A.Ş.",
      invoiceType: "ALIS",
      issueDate: "03.04.2026",
      payableTotal: "999.90",
      vatRates: ["20"],
      status: "review_required",
      draftQuality: "partial_review_required",
      isBalanced: true,
      riskFlags: [],
      parseNotes: [],
      reviewReasonCodes: ["counterparty_not_found"],
      productLineHint: "Kolay Soft e-fatura hizmeti",
      productCategory: "E-fatura hizmeti",
      productConfidence: 94,
      businessRelevanceStatus: "genel_gider",
      businessRelevanceConfidence: 94,
      businessRelevanceReason: "Kalem sektörler arası genel gider niteliğinde görünüyor.",
      businessRelevanceEvidence: ["matched:kolay soft", "general_expense"],
      aiClassificationUsed: false,
      aiClassificationProvider: "static_rules",
      aiClassificationSkippedReason: "static_high_confidence",
      aiClassificationReason: "",
      aiEstimatedInputChars: 45,
      learningRuleApplied: false,
      learningRuleScope: "",
      learningRuleReason: "",
      exportStatus: "review_required",
      selectedExpenseAccount: "770.01",
      selectedVatAccount: "191.01",
      selectedSupplierAccount: "320.01",
      counterpartyMatchCode: "",
      counterpartyMatchConfidence: 0,
      counterpartyMatchReason: "not_found",
      processingMode: "ai_assisted_draft",
      draftDecisionSource: "static_rules_ai_assisted_draft",
      deterministicChecks: ["amount_positive", "single_vat_rate", "balanced_entry", "counterparty_missing", "client_onboarding_ready"],
      exportGateReason: "Cari eşleşmesi net olmadığı için export kapalı.",
      draftLines: [
        { account_code: "770.01", description: "Gider", debit: "833.25", credit: "0.00" },
        { account_code: "191.01", description: "İndirilecek KDV", debit: "166.65", credit: "0.00" },
        { account_code: "320.01", description: "Satıcı cari", debit: "0.00", credit: "999.90" },
      ],
    },
    {
      chartFileName: "PILOT ISITME MERKEZI HESAP PLANI.xlsx",
      fileName: "mayis-banka-ekstresi.xlsx",
      providerHint: "Demo Banka",
      invoiceType: "bank_statement",
      intakeCategory: "bank_statement",
      issueDate: "31.05.2026",
      payableTotal: "3 hareket",
      vatRates: [],
      status: "review_required",
      draftQuality: "statement_review_required",
      isBalanced: true,
      riskFlags: ["statement_accountant_approval_required"],
      parseNotes: ["xlsx_statement_parser"],
      reviewReasonCodes: ["statement_accountant_approval_required"],
      productLineHint: "Mayis banka ekstresi",
      productCategory: "Banka hareketleri",
      productConfidence: 88,
      businessRelevanceReason: "Banka ekstresi satirlari deterministik kurallarla ayristirildi.",
      aiClassificationSkippedReason: "phase1_rules_first",
      exportStatus: "review_required",
      selectedExpenseAccount: "102.01",
      selectedVatAccount: "-",
      selectedSupplierAccount: "320.01",
      counterpartyMatchCode: "320.01",
      counterpartyMatchConfidence: 64,
      processingMode: "statement_rules_first",
      draftDecisionSource: "statement_rule_engine",
      deterministicChecks: ["statement_lines_extracted", "direction_normalized", "accountant_approval_required"],
      exportGateReason: "Banka satirlari musavir onayi olmadan export'a girmez.",
      statementAiSummary: "1 AI onerisi hazir; export icin musavir karari gerekir.",
      statementLines: [
        {
          line_no: 1,
          transaction_date: "2026-05-03",
          description: "POS TAHSILAT BLOKE COZUMU",
          amount: "15000.00",
          direction: "in",
          balance_after: "82500.00",
          suggested_account_code: "120.01.001",
          transaction_type: "pos_collection",
          confidence: 88,
          risk_flags: ["statement_accountant_approval_required"],
          review_reason: "POS tahsilati kurali eslesti; musavir onayi bekleniyor.",
        },
        {
          line_no: 2,
          transaction_date: "2026-05-05",
          description: "EFT GONDEREN ABC MEDIKAL TIC LTD",
          amount: "4850.00",
          direction: "out",
          balance_after: "77650.00",
          suggested_account_code: "320.01",
          transaction_type: "unknown",
          confidence: 44,
          risk_flags: ["counterparty_not_found", "statement_accountant_approval_required"],
          review_reason: "Karsi hesap netlesmedi.",
        },
        {
          line_no: 3,
          transaction_date: "2026-05-10",
          description: "BANKA MASRAF KOMISYON",
          amount: "185.50",
          direction: "out",
          balance_after: "77464.50",
          suggested_account_code: "770.03",
          transaction_type: "bank_fee",
          confidence: 91,
          risk_flags: ["statement_accountant_approval_required"],
          review_reason: "Banka masrafi kurali eslesti; onay bekleniyor.",
        },
      ],
      statementEntries: [
        {
          statement_line_no: 1,
          statement_fingerprint: "demo-bank-202605-001",
          source_document_ref: "mayis-banka-ekstresi.xlsx",
          accountant_review_status: "review_required",
          risk_flags: ["statement_accountant_approval_required"],
          lines: [
            { account_code: "102.01", description: "Banka", debit: "15000.00", credit: "0.00" },
            { account_code: "120.01.001", description: "POS tahsilat", debit: "0.00", credit: "15000.00" },
          ],
        },
        {
          statement_line_no: 2,
          statement_fingerprint: "demo-bank-202605-002",
          source_document_ref: "mayis-banka-ekstresi.xlsx",
          accountant_review_status: "review_required",
          risk_flags: ["counterparty_not_found", "statement_accountant_approval_required"],
          lines: [
            { account_code: "320.01", description: "Kontrol bekleyen karsi hesap", debit: "4850.00", credit: "0.00" },
            { account_code: "102.01", description: "Banka", debit: "0.00", credit: "4850.00" },
          ],
        },
        {
          statement_line_no: 3,
          statement_fingerprint: "demo-bank-202605-003",
          source_document_ref: "mayis-banka-ekstresi.xlsx",
          accountant_review_status: "review_required",
          risk_flags: ["statement_accountant_approval_required"],
          lines: [
            { account_code: "770.03", description: "Banka masrafi", debit: "185.50", credit: "0.00" },
            { account_code: "102.01", description: "Banka", debit: "0.00", credit: "185.50" },
          ],
        },
      ],
      statementAiSuggestions: [
        {
          line_no: 2,
          transaction_type: "eft",
          suggested_account_code: "320.01.040",
          confidence: 76,
          reason: "Aciklamadaki ABC Medikal tedarikci sinyali 320.01.040 ile uyumlu.",
          evidence: ["description:ABC MEDIKAL", "direction:out", "ai_schema_validated"],
          risk_flags: ["statement_accountant_approval_required"],
          ai_used: true,
          provider: "replay_provider",
          export_allowed: false,
        },
      ],
      draftLines: [],
    },
  ],
};
